### ISSUE TITLE
Contribution Guidelines?

### ISSUE THREAD

**Issue by FFX01** [inforian/django-notifyAll#3]
I am considering this project for a production application I'm currently working on. I like the idea of having all user notifications move through a central interface. It really is a great idea.

However, I need to make sure that any packages I use for my application are stable and as bug-free as possible. For this reason, I would like to contribute to this project in order to add support for more email providers out of the box and improve test coverage.

Which brings me to my question: What are the guidelines for contributions? Should I just fork and make a pull request? Should I open an issue to make the pull request against? Different maintainers and projects have different systems for accepting contributions and I think it's a bit annoying when people create pull requests out of the blue; that's why I'm asking up front.

**Comment by inforian** [comment]
I am glad that you find this project intersting . 

coming to your question you can create an issue, and send a PR corresponding to that issue.

I have explained in documentation how you can add more providers. if you still have any questions or suggestions feel free to ask.
